import os
import requests
from pathlib import Path
from dotenv import load_dotenv
from datetime import datetime

def send_deals_email():
    load_dotenv()
    
    api_key = os.getenv("RESEND_API_KEY")
    recipient_email = os.getenv("EMAIL_RECIPIENT")
    
    if not api_key or not recipient_email:
        print("Missing RESEND_API_KEY or EMAIL_RECIPIENT. Skipping email.")
        return False, "Missing Resend API credentials in Environment Variables."

    deals_file = Path("deals_today.html")
    if not deals_file.exists():
        print(f"File {deals_file} does not exist. Nothing to send.")
        return False, "deals_today.html file was not generated by tracker."

    html_content = deals_file.read_text(encoding="utf-8")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # The payload to send to Resend
    # Resend allows sending from onboarding@resend.dev to your verified email address for free.
    payload = {
        "from": "SGProof Tracker <onboarding@resend.dev>",
        "to": [recipient_email],
        "subject": f"SGProof Daily Deals Report - {now}",
        "html": html_content
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    try:
        response = requests.post(
            "https://api.resend.com/emails",
            json=payload,
            headers=headers,
            timeout=10
        )
        
        if response.status_code in (200, 201):
            print("Email sent successfully via Resend.")
            return True, "Email sent successfully."
        else:
            error_msg = f"Resend API Error {response.status_code}: {response.text}"
            print(error_msg)
            return False, error_msg

    except Exception as e:
        print(f"Failed to send email via Resend: {e}")
        return False, f"API Request Error: {str(e)}"

if __name__ == "__main__":
    send_deals_email()

