services:
  - type: web
    name: sgproof-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SGPROOF_EMAIL
        sync: false
      - key: SGPROOF_PASSWORD
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENT
        sync: false
